### ISSUE TITLE
Ability to provide a custom commit message

### ISSUE THREAD

**Issue by jmservera** [tech-thinker/push-to-repo#2]
**Is your feature request related to a problem? Please describe.**
I'm using this action to push some files from an organization's private repo to a public one, and the commit message contains the original repo name, and may pose some privacy issues.

**Describe the solution you'd like**
I would like to have a field to provide a custom commit message

**Describe alternatives you've considered**
I don't have any alternative now

**Additional context**
An example is here: https://github.com/MS-ES-DEMO/Well-Architected-Partner-Training

**Comment by mrinjamul** [comment]
@jmservera  yes we know about this. And it's already available. That's why the commit message and the author is configurable. you see the below sample.

```
  deploy-to-github:
    name: Deploy To GitHub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Pushes to Repository
        uses: tech-thinker/push-to-repo@v1.0.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.GIT_PUSH_TOKEN }}
        with:
          source-directory: "build"
          destination-github-username: "username"
          destination-repository-name: "repositoryname"
          target-branch: master
          commit-message: "Update by GitHub Action 🚀"
```
